 name: Djanto Unit Teste
 on: [push]

 jobs:
  django-tests:
    runs-on: windows-latest
    container: 
      image: python:3
    steps:
      - uses: actions/checkout@v2
      - name: Instalando pendencias do pip
        run: pip install --upgrade
          pip install -r requirements.txt

      - name: Fazendo migrações
        working-directory: ./backend
        run: python manage.py migrate

      - name: Excecutar testes
        working-directory: ./backend
        run: python manage.py test --noinput